config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homepage#index'

  resources :restaurants do
    collection do
      get 'mine'
    end

    resources :notes, only: :create

    resources :favorites, only: :create do
      collection do
        post 'kill'
      end
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base

  validates :content, presence: true

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  validates :name, presence: true
  validates :address, presence: true

  has_many :notes

  geocoded_by :address
  after_validation :geocode

  def is_user_favorite?(user_id)
    Favorite.exists?(restaurant_id: self.id, user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
  has_many :restaurants, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    r = Restaurant.find(params[:restaurant_id])

    current_user.favorites.create(restaurant_id: r.id)
    redirect_to restaurant_path(r)
  end

  def kill
    r = Restaurant.find(params[:restaurant_id])
    Favorite.where(user_id: current_user.id, restaurant_id: params[:restaurant_id]).first.destroy
    redirect_to restaurant_path(r)
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @city = request.location.city
  end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @note = @restaurant.notes.create(notes_params)
    if @note.save
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = "You have to write something"
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def notes_params
    params.require(:note).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @search_city = params[:city].capitalize
    @restaurants = Restaurant.near(@search_city + ', CO, US', 5)
    @view = params[:view]
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def mine

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def css_tag_id
    "#{controller.controller_name}-#{controller.action_name}"
  end
end

app/views/homepage/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-md-4 text-justify">
      <h1 class="tagline">Get picky</h1>

      <h3 class="tagline-blurb">Find restaurants that fit your health-conscious lifestyle in</h3>
      <%= form_tag('/restaurants', method: :get, class: 'form-inline') do %>

        <!--value would be city in the future-->
        <%= text_field_tag :city, params[:city], placeholder: 'Boulder or Denver atm', list: 'cities', class: 'form-control input-lg wide' %>
        <%= hidden_field_tag :view, 'list' %>
        <datalist id="cities">
          <option value="Boulder"></option>
          <option value="Denver"></option>
        </datalist>

        <%= submit_tag "GO", class: "btn btn-large btn-primary input-lg front-btn" %>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PickyEater</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body id="<%= css_tag_id %>" class="<%= @search_city == 'Boulder' ? 'boulder' : 'denver' %>">

<!--navbar-->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Picky Eater", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My restaurants", mine_restaurants_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/restaurants/_restaurant_square.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <%= link_to restaurant_path(r) do %>
    <div class="col-md-12 restaurant-square">
      <h1><%= r.name %></h1>
      <h4><%= r.description %></h4>
      <% if r.gluten_free? %>
        <p>  <%= image_tag "gluten-free.jpeg" %>
          100% gluten free</p>
      <% end %>
      <% if r.veggie? %>
        <p>  <%= image_tag "veggie.png" %>
          100% Vegetarian</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 opaque">
      <h1>Restaurants near <%= @search_city %></h1>

      <h2><%= link_to "Search again", root_path %> |
        <% if @view == 'map' %>
          <%= link_to "List View", restaurants_path(city: @search_city, view: "list") %>
        <% else %>
          <%= link_to "Map View", restaurants_path(city: @search_city, view: "map") %>

        <% end %>
        | Sort by gf etc. would go here </h2>
    </div>
  </div>


  <div class="row">
    <% if @view == 'map' %>
      <%= content_tag "div", id: "google-map", class: "col-xs-12 col-md-10 col-md-offset-1", data: {restaurants: @restaurants} do %>
      <% end %>
    <% else %>
      <% @restaurants.each do |restaurant| %>
        <%= render 'restaurants/restaurant_square', r: restaurant %>
      <% end %>
    <% end %>
  </div>


</div>



<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_KEY'] %>&callback=initMap">
</script>

app/views/restaurants/mine.html.erb
<div class="container">


  <div class="row">
    <div class="col-xs-12">
      <h1 class="text-center"><%= current_user.email %>'s Favorite Restaurants</h1>
    </div>
  </div>


  <div class="row">
    <% current_user.favorites.each do |fave| %>
      <%= render 'restaurants/restaurant_square', r: fave.restaurant %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <hr>

      <h1 class="text-center"><%= @restaurant.name %></h1>

      <hr>



    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <h3></h3>
      <%= image_tag "simple-food.jpeg", class: "col-xs-12" %>
    </div>
    <div class="col-xs-12 col-md-4">

      <h3><%= @restaurant.description %></h3>
      <% if user_signed_in? %>

        <% if @restaurant.is_user_favorite?(current_user.id) %>
          <h3><%= link_to "Un-favorite", kill_restaurant_favorites_path(@restaurant), method: :post %></h3>
        <% else %>
          <h3><%= link_to "Mark as favorite", restaurant_favorites_path(@restaurant), method: :create %></h3>
        <% end %>

      <% end %>
    </div>


    <div class="col-xs-12 col-md-4">

      <% if @restaurant.gluten_free? %>

        <h3><%= image_tag 'gluten-free.jpeg' %> 100% gluten free</h3>

      <% end %>

      <% if @restaurant.veggie? %>

        <h3><%= image_tag 'veggie.png' %> 100% vegetarian</h3>

      <% end %>

    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <h4>Notes about this restaurant</h4>


      <% @restaurant.notes.each do |note| %>
        <p>
          <%= note.content %>

        </p>
      <% end %>

    </div>
    <h4></h4>

    <div class="col-xs-12 col-md-6">
      <%= form_for [@restaurant, Note.new] do |f| %>
        <%= f.text_area :content, class: "form-control", placeholder: "Add a note..." %>
        <%= f.submit class: "btn btn-default pull-right" %>
      <% end %>
      <h3 class="alert-warning"><%= flash.alert %></h3>

    </div>
  </div>
  <hr>
  <p>
    Pull in stuff from google api: star rating, photo?, description
    Then put tags for vegan restaurant, 100% vegetarian, partner farms, gluten free etc
  </p>

</div>